global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'drupal-local'
    static_configs:
      - targets: ['drupal_app:80']

  - job_name: 'mysql-local'
    static_configs:
      - targets: ['drupal_mysql:3306']