apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: drupal-production
type: Opaque
stringData:
  mysql-root-password: "YourRootPassword123!"
  mysql-user: "drupaldbadmin"
  mysql-password: "Joel1234"
  mysql-database: "drupal"